config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :candidates, only: %i[index create show]
  resources :votes, only: %i[new index create]
  resources :sessions, only: %i[new destroy] do
    collection do
      get :logout, to: 'sessions#destroy'
    end
  end
  # NOTE: Disabling the user resource since it is not used directly in the application
  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#new'
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id          :string           not null, primary key
#  email       :string           not null
#  postal_code :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :email, presence: true, uniqueness: true, email: true
  validates :postal_code, presence: true

  def self.authenticate!(email:, postal_code:)
    user = find_by_email(email)
    return false unless user

    user.postal_code == postal_code
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :check_authentication!, only: %i[create]
  skip_before_action :require_authentication!, only: %i[new create]

  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/new
  def new
    redirect_to votes_url, notice: t('sessions.already_logged_in') if current_user

    @user = User.new(email: Faker::Internet.email, postal_code: Faker::Address.zip_code)
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  def create
    email, postal_code = user_params.values_at(:email, :postal_code)
    @user = User.find_by(**user_params) if User.authenticate!(email:, postal_code:)
    @user ||= User.new(user_params)

    if @user.persisted?
      redirect_to new_vote_path, notice: t('users.already_registered')
    elsif @user.save
      redirect_to new_vote_path, notice: t('users.create_success')
    else
      render :new, status: :unprocessable_entity
    end
  ensure
    authenticate_user!(@user) if @user&.persisted?
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.permit(user: %i[email postal_code])[:user]
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_has_voted?
    return false unless @current_user

    @current_user.votes.any?
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, html: { class: "space-y-6" }) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, class: center_input_label_classes %>
    <div class="mt-2">
      <%= form.text_field :email, class: center_input_classes %>
    </div>
  </div>

  <div>
    <%= form.label :postal_code, class: center_input_label_classes %>
    <%= form.text_field :postal_code, class: center_input_classes %>
  </div>

  <div>
    <%= form.submit(value: "Continue to vote", class: center_button_classes) %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Postal code:</strong>
    <%= user.postal_code %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<% content_for :form_body do %>
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm space-y-6">
    <%= form_header "New voting session" %>

    <%= render "form", user: @user %>

    <hr />

    <%= render "shared/link_to_election_results" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>