config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :candidates, only: %i[index create show]
  resources :votes, only: %i[new index create]
  resources :sessions, only: %i[new destroy] do
    collection do
      get :logout, to: 'sessions#destroy'
    end
  end
  # NOTE: Disabling the user resource since it is not used directly in the application
  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#new'
end

app/views/shared/_centered_form.html.erb
<div class="flex min-h-full flex-col justify-center px-8 py-12">
  <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-screen-md space-y-6">
    <%= yield :form_body %>
  </div>
</div>

app/views/shared/_link_to_election_results.html.erb
<div class="mt-10 text-center text-sm text-gray-500">
  <%= link_to "Election results", votes_url %>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/votes" class="flex items-center space-x-3 rtl:space-x-reverse">
      VOTE.WEBSITE
    </a>
    <div class="flex md:order-2 space-x-3 rtl:space-x-reverse">
      <% if authenticated? %>
        <span class="flex items-center space-x-3 rtl:space-x-reverse">Signed in as <%= @current_user.email %></span>
        <%= button_to "Log out", @current_session, method: :delete, class: light_button_classes %>
      <% else %>
        <%= button_to "Log in", new_session_url, method: :get, class: light_button_classes %>
      <% end %>
      <!--
      <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
      -->
    </div>
    <!--
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="#" class="block py-2 px-3 md:p-0 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:dark:text-blue-500" aria-current="page">Home</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 d:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Services</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
        </li>
      </ul>
    </div>
    -->
  </div>
</nav>