config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :candidates, only: %i[index create show]
  resources :votes, only: %i[new index create]
  resources :sessions, only: %i[new destroy] do
    collection do
      get :logout, to: 'sessions#destroy'
    end
  end
  # NOTE: Disabling the user resource since it is not used directly in the application
  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#new'
end

app/models/candidate.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: candidates
#
#  id         :string           not null, primary key
#  full_name  :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Candidate < ApplicationRecord
  BALLOT_LIMIT = 10

  has_many :votes

  validates :full_name, presence: true, uniqueness: { case_sensitive: false }
  validate :cannot_exceed_ballot_limit

  def cannot_exceed_ballot_limit
    return unless Candidate.all.count >= BALLOT_LIMIT

    errors.add(:base, "You cannot have more than #{BALLOT_LIMIT} candidates")
  end
end

app/controllers/candidates_controller.rb
# frozen_string_literal: true

class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[show edit update destroy]

  # GET /candidates
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  def show; end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
  end

  # GET /candidates/1/edit
  def edit; end

  # POST /candidates
  def create
    @candidate = Candidate.new(candidate_params)
    @vote = Vote.new(candidate: @candidate, user: current_user)

    if @candidate.save && @vote.save
      redirect_to votes_path, notice: t('votes.write_in_success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /candidates/1
  def update
    if @candidate.update(candidate_params)
      redirect_to @candidate, notice: 'Candidate was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /candidates/1
  def destroy
    @candidate.destroy
    redirect_to candidates_url, notice: 'Candidate was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_candidate
    @candidate = Candidate.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def candidate_params
    params.permit(candidate: %i[full_name])[:candidate] || {}
  end
end

app/helpers/candidates_helper.rb
# frozen_string_literal: true

module CandidatesHelper
end

app/views/candidates/_candidate.html.erb
<div id="<%= dom_id candidate %>">
  <p>
    <strong>Full name:</strong>
    <%= candidate.full_name %>
  </p>

</div>

app/views/candidates/_form.html.erb
<% candidate_submit_label ||= "Save candidate" %>
<%= form_with(model: candidate, html: { class: 'space-y-6' }) do |form| %>
  <% if candidate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :full_name, style: "display: block" %>
    <%= form.text_field :full_name, placeholder: "Enter name..." %>
  </div>

  <div>
    <%= form.submit(value: candidate_submit_label, class: button_classes) %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Show this candidate", @candidate %> |
  <%= link_to "Back to candidates", candidates_path %>
</div>

app/views/candidates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Candidates</h1>

<div id="candidates">
  <% @candidates.each do |candidate| %>
    <%= render candidate %>
    <p>
      <%= link_to "Show this candidate", candidate %>
    </p>
  <% end %>
</div>

<%= link_to "Cast a new vote", new_vote_path %>

app/views/candidates/new.html.erb
<% content_for :form_body do %>
<div class="sm:mx-auto sm:w-full sm:max-w-sm space-y-6">
  <%= form_header 'New candidate', centered: false %>

  <%= render "form", candidate: @candidate %>

  <br>

  <div>
    <%= link_to "Back to new vote", new_vote_url %>
  </div>
</div>
<% end %>

app/views/candidates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @candidate %>

<div>
  <%= link_to "Edit this candidate", edit_candidate_path(@candidate) %> |
  <%= link_to "Back to candidates", candidates_path %>

  <%= button_to "Destroy this candidate", @candidate, method: :delete %>
</div>