config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :candidates, only: %i[index create show]
  resources :votes, only: %i[new index create]
  resources :sessions, only: %i[new destroy] do
    collection do
      get :logout, to: 'sessions#destroy'
    end
  end
  # NOTE: Disabling the user resource since it is not used directly in the application
  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#new'
end

app/models/vote.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: votes
#
#  id           :string           not null, primary key
#  candidate_id :string           not null
#  user_id      :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Vote < ApplicationRecord
  belongs_to :candidate
  belongs_to :user

  validate :only_1_vote_per_user

  private

  def only_1_vote_per_user
    return if user.votes.count < 1

    errors.add(:base, I18n.t('votes.ballot_already_voted'))
  end
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  skip_before_action :require_authentication!, only: %i[index]
  before_action :set_candidate, only: %i[create]
  before_action :set_candidates, only: %i[new create]
  after_action :broadcast_ballot_tally, only: %i[create], if: -> { @vote&.persisted? }

  # GET /votes
  def index
    @votes = tallied_votes
  end

  # GET /votes/1
  def show; end

  # GET /votes/new
  def new
    existing_vote = Vote.find_by(user: current_user)
    if existing_vote
      redirect_to votes_path, notice: t('votes.ballot_already_voted')
      return
    end

    @vote = Vote.new
    @candidate = Candidate.new
  end

  # POST /votes
  def create
    # TODO: Attempt saving a candidate ONLY if there is candidate data
    @candidate = creating_candidate? ? Candidate.new(candidate_params) : Candidate.new
    @vote = Vote.new(vote_params.merge(user_id: current_user.id))

    if creating_candidate? && @candidate&.save && @vote.save
      redirect_to votes_path, notice: t('votes.write_in_success')
    elsif @vote.save
      redirect_to votes_path, notice: t('votes.ballot_success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def broadcast_ballot_tally
    ActionCable.server.broadcast 'election_live_polls', { ballots_cast: total_votes }
  end

  def total_votes
    tallied_votes.sum(&:total_votes)
  end

  def tallied_votes
    @tallied_votes ||= Candidate.select('candidates.full_name, count(votes.candidate_id) as total_votes')
                                .joins(:votes).group('candidates.full_name').order('2 desc')
  end

  # Use callbacks to share common setup or constraints between actions.

  def set_candidates
    @candidates = Candidate.all
  end

  def set_candidate
    @candidate ||= Candidate.find_by_id(vote_params[:candidate_id])
    @candidate ||= Candidate.new
  end

  # Only allow a list of trusted parameters through.
  def vote_params
    params.permit(vote: %i[candidate_id user_id])[:vote] || {}
  end

  def candidate_params
    params.permit(candidate: %i[full_name])[:candidate]
  end

  def creating_candidate?
    params[:candidate].present?
  end
end

app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_with(model: vote, html: { class: 'space-y-6' }) do |form| %>
  <% if vote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- TODO: Implement the form for casting a vote by select a radio button for a candidate -->
  <div id="candidates">
    <% @candidates.each do |candidate| %>
      <div class="candidate">
        <!-- TODO calculate snake case for candidate name to use in label_for -->
        <%= form.radio_button :candidate_id, candidate.id %>
        <%= form.label candidate.full_name %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit(value: "Vote", class: button_classes) %>
  </div>
<% end %>

app/views/votes/_vote.html.erb
<div id="<%= dom_id vote %>">
</div>

app/views/votes/index.html.erb
<% content_for :form_body do %>
  <p style="color: green"><%= notice %></p>

  <div class="relative space-y-6 overflow-x-auto justify-center">
    <%= form_header "Election results" %>

    <% if @votes.none? %>
      <div class="flex items-center justify-center px-5 py-5">
        <p class="text-gray-500 dark:text-gray-400 justify-center">No votes yet</p>
      </div>
    <% else %>
      <table id="votes" class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-200 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <th scope="col" class="px-10 py-3">Candidate</th>
          <th scope="col" class="px-2 py-3">Votes</th>
        </tr>
        </thead>
        <tbody>
        <% @votes.each do |candidate_summary| %>
          <tr class="bg-white border-b dark:bg-gray-800 white:border-gray-700">
            <th scope="row" class="px-10 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
              <%= candidate_summary.full_name %>
            </th>
            <td class="px-2 py-4"><%= candidate_summary.total_votes %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="flex justify-center space-x-4">
    <%= button_to "New vote", new_vote_path,
                  class: "#{button_classes}#{user_has_voted? ? ' cursor-not-allowed' : ''}",
                  disable: user_has_voted?, method: :get %>
    <% unless @current_session.nil? %>
      <%= button_to "Done", session_url(@current_session), class: button_classes, method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/votes/new.html.erb
<% content_for :form_body do %>
  <div class="sm:mx-auto sm:w-full sm:max-w-sm space-y-6">
    <%= form_header 'Cast your vote today!', centered: false %>

    <%if @candidates.none? %>
      <div>
        <p>There are no candidates on the ballot yet. Write in the full name of your candidate in the form below.</p>
      </div>
    <% else %>
      <%= render "form", vote: @vote %>
    <% end %>

    <hr />

    <%= form_header 'Or add a new candidate', centered: false %>

    <%= render "candidates/form", candidate: @candidate, candidate_submit_label: 'Write in and vote' %>

    <div>
      <%= link_to "Election results", votes_path %>
    </div>
  </div>
<% end %>

app/views/votes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @vote %>

<div>
  <%= link_to "Back to votes", votes_path %> |
  <%= link_to "Cast a new vote", new_vote_path %>
</div>